# Generated by Django 4.2.4 on 2024-01-02 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('program_name', models.CharField(max_length=50)),
                ('wbs_number', models.CharField(max_length=30)),
                ('oem', models.CharField(max_length=20)),
            ],
        ),
    ]
