# Generated by Django 4.2.4 on 2024-08-08 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='test',
            options={'permissions': (('test_page_only', 'Can view test'),)},
        ),
    ]
