# Generated by Django 4.2.13 on 2024-06-12 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fixtures',
            fields=[
                ('fixture_name', models.CharField(max_length=50, null=True, verbose_name='Fixture Name')),
                ('product_id', models.CharField(max_length=10, null=True, verbose_name='Product ID')),
                ('number_of_DUTs', models.CharField(max_length=30, null=True, verbose_name='Number of DUTs')),
                ('comments', models.CharField(max_length=200, null=True, verbose_name='Comments')),
                ('program_id', models.SmallAutoField(primary_key=True, serialize=False)),
            ],
        ),
    ]
