# Generated by Django 4.2.4 on 2024-03-18 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='created',
        ),
    ]
