# Generated by Django 4.2.4 on 2024-03-18 11:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0002_remove_test_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
