# Generated by Django 4.2.4 on 2024-01-02 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0002_test_delete_program'),
    ]

    operations = [
        migrations.CreateModel(
            name='test1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('a', models.CharField(max_length=50)),
                ('b', models.IntegerField()),
                ('d', models.BigIntegerField()),
                ('e', models.DateField()),
                ('f', models.DateTimeField()),
                ('g', models.DecimalField(decimal_places=2, max_digits=5)),
                ('h', models.DurationField()),
                ('i', models.FloatField()),
                ('k', models.IntegerField()),
                ('l', models.JSONField()),
                ('m', models.PositiveBigIntegerField()),
                ('n', models.PositiveIntegerField()),
                ('o', models.PositiveSmallIntegerField()),
                ('p', models.SmallIntegerField()),
                ('q', models.TextField()),
                ('r', models.TimeField()),
            ],
        ),
        migrations.DeleteModel(
            name='test',
        ),
    ]
