# Generated by Django 4.2.4 on 2024-08-08 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0002_alter_test_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='test',
            options={},
        ),
    ]
