# Generated by Django 4.2.9 on 2024-02-14 16:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0002_product_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
