# Generated by Django 4.2.4 on 2024-03-20 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0003_remove_chamberlog_ambient_temp_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='datetimetest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('legacydatetime', models.DateTimeField()),
                ('legacytime', models.TimeField()),
            ],
        ),
    ]
