# Generated by Django 4.2.13 on 2024-06-12 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0003_alter_fixtures_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fixtures',
            name='comments',
            field=models.CharField(max_length=1000, null=True, verbose_name='Comments'),
        ),
    ]
