# Generated by Django 4.2.4 on 2024-01-02 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0003_test1_delete_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test1',
            name='k',
        ),
    ]
