# Generated by Django 4.2.9 on 2024-02-14 17:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0004_alter_program_program_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='chamberloginfo',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
