# Generated by Django 4.2.13 on 2024-06-12 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0004_alter_fixtures_comments'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fixtures',
            old_name='program_id',
            new_name='Fixtures_id',
        ),
    ]
