# Generated by Django 4.2.4 on 2024-05-23 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0004_alter_test_supervisor_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcomponent',
            name='hardware',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='subcomponent',
            name='software',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='test',
            name='supervisor_comments',
            field=models.CharField(blank=True, max_length=4000, null=True),
        ),
    ]
