# Generated by Django 4.2.4 on 2024-01-02 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0004_remove_test1_k'),
    ]

    operations = [
        migrations.AddField(
            model_name='test1',
            name='s',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
