# Generated by Django 4.2.13 on 2024-06-18 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0005_rename_program_id_fixtures_fixtures_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='scheduling',
            field=models.TextField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='test',
            name='status',
            field=models.TextField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='test',
            name='supervisor_comments',
            field=models.TextField(max_length=18000, null=True),
        ),
        migrations.AlterField(
            model_name='test',
            name='test_description',
            field=models.TextField(max_length=150, null=True),
        ),
    ]
