# Generated by Django 4.2.4 on 2024-03-20 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0005_datetimetest_datetime_datetimetest_time'),
    ]

    operations = [
        migrations.DeleteModel(
            name='datetimetest',
        ),
    ]
