# Generated by Django 4.2.4 on 2024-05-29 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0005_subcomponent_hardware_subcomponent_software_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subcomponent',
            old_name='component_id',
            new_name='subcomponent_id',
        ),
        migrations.RenameField(
            model_name='subcomponent',
            old_name='component_name',
            new_name='subcomponent_name',
        ),
    ]
