# Generated by Django 4.2.9 on 2024-02-15 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0006_remove_chamberlog_test_id_chamberlog_log_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='program_name',
            field=models.CharField(max_length=50, null=True, unique=True, verbose_name='Program'),
        ),
    ]
