# Generated by Django 4.2.13 on 2024-06-18 10:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0006_alter_test_scheduling_alter_test_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='cage_id',
            field=models.ForeignKey(db_column='cage_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='database.cage', verbose_name='Cage'),
        ),
        migrations.AlterField(
            model_name='test',
            name='chamber_id',
            field=models.ForeignKey(db_column='chamber_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='database.chamber', verbose_name='Chamber'),
        ),
        migrations.AlterField(
            model_name='test',
            name='dar_id',
            field=models.ForeignKey(db_column='dar_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='database.dar', verbose_name='DAR'),
        ),
        migrations.AlterField(
            model_name='test',
            name='lab_id',
            field=models.ForeignKey(db_column='lab_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='database.lab', verbose_name='Lab'),
        ),
        migrations.AlterField(
            model_name='test',
            name='technician_id',
            field=models.ForeignKey(db_column='technician_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='database.technician', verbose_name='Technician'),
        ),
        migrations.AlterField(
            model_name='test',
            name='test_type_id',
            field=models.ForeignKey(db_column='test_type_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='database.testtype', verbose_name='Test Type'),
        ),
    ]
