# Generated by Django 4.2.4 on 2024-05-30 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0006_rename_component_id_subcomponent_subcomponent_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='harness',
            name='comments',
            field=models.CharField(max_length=100),
        ),
    ]
