# Generated by Django 4.2.4 on 2024-01-02 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0006_remove_test1_id_alter_test1_a_alter_test1_b_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test1',
            name='d',
            field=models.BigIntegerField(null=True),
        ),
    ]
