# Generated by Django 4.2.4 on 2024-01-02 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0007_alter_test1_d'),
    ]

    operations = [
        migrations.AddField(
            model_name='test1',
            name='t',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
