# Generated by Django 4.2.4 on 2024-03-20 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0007_remove_chamberlog_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='chamberlog',
            name='timestamp',
            field=models.DateTimeField(null=True),
        ),
    ]
