# Generated by Django 4.2.4 on 2024-05-30 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0007_alter_harness_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='harness',
            name='comments',
            field=models.CharField(max_length=150),
        ),
    ]
