# Generated by Django 4.2.9 on 2024-02-15 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0007_alter_program_program_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='program_name',
            field=models.CharField(max_length=50, null=True, verbose_name='Program'),
        ),
    ]
