# Generated by Django 4.2.4 on 2024-02-23 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0008_alter_program_program_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='total_hours',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='chamber',
            name='humidity',
            field=models.CharField(max_length=10, null=True, verbose_name='Humidity'),
        ),
        migrations.AlterField(
            model_name='chamber',
            name='working_condition',
            field=models.CharField(max_length=50, null=True, verbose_name='Working Condition'),
        ),
        migrations.AlterField(
            model_name='chamberlog',
            name='status',
            field=models.CharField(max_length=20, null=True, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='chamberloginfo',
            name='pretest_inspection_and_photo',
            field=models.CharField(max_length=10, null=True, verbose_name='Pretest Inspection and Photo'),
        ),
        migrations.AlterField(
            model_name='chamberloginfo',
            name='system_restriction_record',
            field=models.CharField(max_length=10, null=True, verbose_name='System Restriction Record'),
        ),
        migrations.AlterField(
            model_name='chamberloginfo',
            name='trial_run_record_and_process',
            field=models.CharField(max_length=10, null=True, verbose_name='Trial Run Record And Process'),
        ),
        migrations.AlterField(
            model_name='dar',
            name='working_condition',
            field=models.CharField(max_length=50, null=True, verbose_name='Working Condition'),
        ),
        migrations.AlterField(
            model_name='darchannel',
            name='can',
            field=models.CharField(max_length=50, null=True, verbose_name='CAN'),
        ),
        migrations.AlterField(
            model_name='darchannel',
            name='lin',
            field=models.CharField(max_length=50, null=True, verbose_name='LIN'),
        ),
        migrations.AlterField(
            model_name='darchannel',
            name='pwn',
            field=models.CharField(max_length=50, null=True, verbose_name='PWN'),
        ),
        migrations.AlterField(
            model_name='harness',
            name='dunk_testing',
            field=models.CharField(max_length=10, null=True, verbose_name='Dunk Testing'),
        ),
        migrations.AlterField(
            model_name='harness',
            name='harness_connector_condition',
            field=models.CharField(max_length=10, null=True, verbose_name='Harness Connector Condition'),
        ),
        migrations.AlterField(
            model_name='harness',
            name='insulation_condition',
            field=models.CharField(max_length=10, null=True, verbose_name='Insulation Condition'),
        ),
        migrations.AlterField(
            model_name='harness',
            name='rtv_condition',
            field=models.CharField(max_length=10, null=True, verbose_name='RTV Condition'),
        ),
        migrations.AlterField(
            model_name='harness',
            name='test_screening_resutl',
            field=models.CharField(max_length=10, null=True, verbose_name='Test Screening Result'),
        ),
        migrations.AlterField(
            model_name='laptop',
            name='keyboard_cover',
            field=models.CharField(max_length=10, null=True, verbose_name='Keyboard Cover'),
        ),
        migrations.AlterField(
            model_name='program',
            name='phase',
            field=models.CharField(max_length=20, null=True, verbose_name='Phase'),
        ),
        migrations.AlterField(
            model_name='program',
            name='status',
            field=models.CharField(max_length=20, null=True, verbose_name='Status'),
        ),
    ]
