# Generated by Django 4.2.4 on 2024-01-02 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0008_test1_t'),
    ]

    operations = [
        migrations.AddField(
            model_name='test1',
            name='u',
            field=models.CharField(max_length=5, null=True),
        ),
    ]
