# Generated by Django 4.2.4 on 2024-03-20 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0008_chamberlog_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chamberlog',
            name='chamber_id',
            field=models.SmallIntegerField(),
        ),
    ]
