# Generated by Django 4.2.4 on 2024-05-30 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0009_alter_harness_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='harness',
            name='comments',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='harness',
            name='dunk_testing',
            field=models.CharField(blank=True, max_length=4, null=True, verbose_name='Dunk Testing'),
        ),
        migrations.AlterField(
            model_name='harness',
            name='harness_connector_condition',
            field=models.CharField(blank=True, max_length=4, null=True, verbose_name='Harness Connector Condition'),
        ),
        migrations.AlterField(
            model_name='harness',
            name='harness_name',
            field=models.CharField(max_length=40, unique=True),
        ),
        migrations.AlterField(
            model_name='harness',
            name='insulation_condition',
            field=models.CharField(blank=True, max_length=4, null=True, verbose_name='Insulation Condition'),
        ),
        migrations.AlterField(
            model_name='harness',
            name='rtv_condition',
            field=models.CharField(blank=True, max_length=4, null=True, verbose_name='RTV Condition'),
        ),
        migrations.AlterField(
            model_name='harness',
            name='storage_location',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='harness',
            name='test_screening_result',
            field=models.CharField(blank=True, max_length=4, null=True, verbose_name='Test Screening Result'),
        ),
    ]
