# Generated by Django 4.2.4 on 2024-03-13 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0009_test_total_hours_alter_chamber_humidity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chamberlog',
            name='demo',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
