# Generated by Django 4.2.4 on 2024-01-02 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0009_test1_u'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test1',
            name='u',
        ),
        migrations.AddField(
            model_name='test1',
            name='v',
            field=models.CharField(max_length=5, null=True),
        ),
    ]
