# Generated by Django 4.2.4 on 2024-03-20 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0009_alter_chamberlog_chamber_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ChamberLog',
        ),
    ]
