# Generated by Django 4.2.4 on 2024-03-20 13:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0010_delete_chamberlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChamberLog',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField()),
                ('circuit_number', models.SmallIntegerField()),
                ('total_hours', models.SmallIntegerField()),
                ('status', models.CharField(max_length=20, null=True, verbose_name='Status')),
                ('chamber_id', models.SmallIntegerField()),
                ('dut_id', models.IntegerField(null=True)),
                ('comments', models.CharField(max_length=300, null=True)),
                ('technician', models.CharField(max_length=100, null=True)),
                ('shaker_direction', models.CharField(max_length=100, null=True)),
                ('dar_id', models.SmallIntegerField(null=True)),
                ('cage_id', models.SmallIntegerField(null=True)),
                ('log_id', models.ForeignKey(db_column='log_id', on_delete=django.db.models.deletion.CASCADE, to='database.chamberloginfo')),
            ],
        ),
    ]
