# Generated by Django 4.2.4 on 2024-05-30 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0010_alter_harness_comments_alter_harness_dunk_testing_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='harness',
            name='harness_name',
            field=models.CharField(max_length=40),
        ),
    ]
