# Generated by Django 4.2.4 on 2024-03-13 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0010_chamberlog_demo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chamberlog',
            name='demo',
        ),
    ]
