# Generated by Django 4.2.4 on 2024-03-13 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0011_remove_chamberlog_demo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chamberlog',
            name='comments',
        ),
    ]
