# Generated by Django 4.2.4 on 2024-01-02 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0011_program_delete_test1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='program',
            name='id',
        ),
        migrations.AddField(
            model_name='program',
            name='enterproj_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='program',
            name='phase',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='program',
            name='status',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='program',
            name='oem',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='program',
            name='program_name',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='program',
            name='wbs_number',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
