# Generated by Django 4.2.4 on 2024-05-30 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0011_alter_harness_harness_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='enterproj_id',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='EnterProj ID'),
        ),
        migrations.AlterField(
            model_name='program',
            name='phase',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Phase'),
        ),
    ]
