# Generated by Django 4.2.4 on 2024-03-25 13:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0011_chamberlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chamberlog',
            name='cage_id',
            field=models.ForeignKey(db_column='cage_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='database.cage'),
        ),
        migrations.AlterField(
            model_name='chamberlog',
            name='chamber_id',
            field=models.ForeignKey(db_column='chamber_id', on_delete=django.db.models.deletion.CASCADE, to='database.chamber'),
        ),
        migrations.AlterField(
            model_name='chamberlog',
            name='dar_id',
            field=models.ForeignKey(db_column='dar_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='database.dar'),
        ),
    ]
