# Generated by Django 4.2.4 on 2024-03-14 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0012_remove_chamberlog_comments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chamberlog',
            name='ambient_temp',
        ),
        migrations.RemoveField(
            model_name='chamberlog',
            name='current',
        ),
        migrations.RemoveField(
            model_name='chamberlog',
            name='fluid_temp',
        ),
        migrations.RemoveField(
            model_name='chamberlog',
            name='head',
        ),
        migrations.RemoveField(
            model_name='chamberlog',
            name='lin_speed',
        ),
        migrations.RemoveField(
            model_name='chamberlog',
            name='system_pressure',
        ),
        migrations.RemoveField(
            model_name='chamberlog',
            name='voltage',
        ),
        migrations.RemoveField(
            model_name='chamberloginfo',
            name='chamber_id',
        ),
        migrations.RemoveField(
            model_name='chamberloginfo',
            name='program_id',
        ),
        migrations.RemoveField(
            model_name='chamberloginfo',
            name='technician_id',
        ),
        migrations.RemoveField(
            model_name='test',
            name='setup_date',
        ),
        migrations.RemoveField(
            model_name='test',
            name='status_log',
        ),
        migrations.AddField(
            model_name='chamber',
            name='max_daily_hours',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='chamberlog',
            name='cage_id',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='chamberlog',
            name='chamber_id',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='chamberlog',
            name='comments',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='chamberlog',
            name='dar_id',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='chamberlog',
            name='dut_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='chamberlog',
            name='shaker_direction',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='chamberlog',
            name='technician',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='chamberloginfo',
            name='chamber_profile',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='chamberloginfo',
            name='coolant',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='chamberloginfo',
            name='pump_profile',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='chamberloginfo',
            name='shaker_profile',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='chamberloginfo',
            name='temperature',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='chamberloginfo',
            name='test_profile',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='chamber',
            name='cooling_power',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='chamber',
            name='heating_gradient',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='chamber',
            name='heating_power',
            field=models.SmallIntegerField(null=True),
        ),
    ]
