# Generated by Django 4.2.4 on 2024-03-25 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0012_alter_chamberlog_cage_id_alter_chamberlog_chamber_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chamber',
            name='billing_category',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
