# Generated by Django 4.2.4 on 2024-03-14 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0013_remove_chamberlog_ambient_temp_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chamberlog',
            name='comments',
        ),
    ]
