# Generated by Django 4.2.4 on 2024-01-03 21:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0013_lab_skill_technician_testmap_technician_skill_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_family', models.CharField(max_length=10, null=True)),
                ('platform', models.CharField(max_length=15, null=True)),
                ('communication_protocol', models.CharField(max_length=15, null=True)),
                ('voltage', models.CharField(max_length=3, null=True)),
                ('variant', models.CharField(max_length=30, null=True)),
                ('program_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='database.program')),
            ],
        ),
        migrations.AlterField(
            model_name='dut',
            name='product_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='database.product1'),
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
