# Generated by Django 4.2.4 on 2024-03-26 10:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0013_chamber_billing_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chamberlog',
            name='dut_id',
            field=models.ForeignKey(db_column='dut_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='database.dut'),
        ),
    ]
