# Generated by Django 4.2.4 on 2024-03-26 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0014_alter_chamberlog_dut_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chamberlog',
            name='dut_id',
        ),
    ]
