# Generated by Django 4.2.4 on 2024-05-30 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0014_dut_pedigree_alter_cage_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dut',
            name='dut_name',
            field=models.CharField(max_length=40, unique=True, verbose_name='DUT name'),
        ),
    ]
