# Generated by Django 4.2.4 on 2024-01-03 21:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0014_product1_alter_dut_product_id_delete_product'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Product1',
            new_name='Product',
        ),
    ]
