# Generated by Django 4.2.4 on 2024-03-14 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0014_remove_chamberlog_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='chamberlog',
            name='comments',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
