# Generated by Django 4.2.4 on 2024-03-26 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0015_remove_chamberlog_dut_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test_dut',
            name='date',
        ),
    ]
