# Generated by Django 4.2.4 on 2024-06-04 10:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0015_alter_dut_dut_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dut',
            name='product_id',
            field=models.ForeignKey(db_column='product_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='database.product', verbose_name='Product - Program'),
        ),
        migrations.AlterField(
            model_name='testmap',
            name='test_map_name',
            field=models.CharField(max_length=100, null=True, verbose_name='Test Map name'),
        ),
    ]
