# Generated by Django 4.2.4 on 2024-06-04 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0016_alter_dut_product_id_alter_testmap_test_map_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testmap',
            name='tr',
            field=models.CharField(max_length=14, null=True, verbose_name='TR'),
        ),
    ]
