# Generated by Django 4.2.4 on 2024-06-04 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0017_alter_testmap_tr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testmap',
            name='tr',
            field=models.CharField(default='', max_length=14, null=True, verbose_name='TR'),
        ),
    ]
