# Generated by Django 4.2.4 on 2024-03-28 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0017_remove_test_harness_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='test_dut',
            name='date_inserted',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='test_dut',
            name='date_removed',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='test_harness',
            name='date_inserted',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='test_harness',
            name='date_removed',
            field=models.DateField(null=True),
        ),
    ]
