# Generated by Django 4.2.4 on 2024-06-04 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0018_alter_testmap_tr'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='program_id',
        ),
    ]
