# Generated by Django 4.2.4 on 2024-03-28 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0018_test_dut_date_inserted_test_dut_date_removed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test_dut',
            name='date_inserted',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='test_dut',
            name='date_removed',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='test_harness',
            name='date_inserted',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='test_harness',
            name='date_removed',
            field=models.DateTimeField(null=True),
        ),
    ]
