# Generated by Django 4.2.4 on 2024-06-05 16:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0019_remove_test_program_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='product_id',
        ),
        migrations.RemoveField(
            model_name='test',
            name='test_map_id',
        ),
        migrations.AddField(
            model_name='test',
            name='product',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='test',
            name='program_id',
            field=models.ForeignKey(db_column='program_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='database.program', verbose_name='Program'),
        ),
        migrations.AddField(
            model_name='test',
            name='test_map',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='dut',
            name='product_id',
            field=models.ForeignKey(db_column='product_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='database.product', verbose_name='Product'),
        ),
    ]
