# Generated by Django 4.2.4 on 2024-03-28 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0019_alter_test_dut_date_inserted_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test_dut',
            name='date_inserted',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='test_harness',
            name='date_inserted',
            field=models.DateTimeField(),
        ),
    ]
