# Generated by Django 4.2.4 on 2024-04-10 15:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0020_alter_test_dut_date_inserted_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subcomponent',
            fields=[
                ('component_name', models.CharField(max_length=100)),
                ('component_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('dut_id', models.ForeignKey(db_column='dut_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='database.dut')),
            ],
        ),
    ]
