# Generated by Django 4.2.4 on 2024-06-06 10:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0021_remove_test_test_map_test_tr_alter_test_product_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='tr',
        ),
        migrations.AddField(
            model_name='test',
            name='test_map_id',
            field=models.ForeignKey(db_column='test_map_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='database.testmap', verbose_name='Test Map'),
        ),
    ]
