# Generated by Django 4.2.4 on 2024-01-04 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0021_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='program_name',
        ),
        migrations.RemoveField(
            model_name='technician',
            name='lab_name',
        ),
        migrations.RemoveField(
            model_name='technician_skill',
            name='skill',
        ),
        migrations.RemoveField(
            model_name='technician_skill',
            name='technician_name',
        ),
        migrations.RemoveField(
            model_name='testmap',
            name='program_name',
        ),
        migrations.DeleteModel(
            name='DUT',
        ),
        migrations.DeleteModel(
            name='Lab',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.DeleteModel(
            name='Program',
        ),
        migrations.DeleteModel(
            name='Skill',
        ),
        migrations.DeleteModel(
            name='Technician',
        ),
        migrations.DeleteModel(
            name='Technician_Skill',
        ),
        migrations.DeleteModel(
            name='TestMap',
        ),
    ]
