# Generated by Django 4.2.4 on 2024-06-06 10:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0022_remove_test_tr_test_test_map_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='product',
        ),
        migrations.AddField(
            model_name='test',
            name='product_id',
            field=models.ForeignKey(db_column='product_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='database.product', verbose_name='Product'),
        ),
    ]
