# Generated by Django 4.2.4 on 2024-01-04 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0023_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dar_laptop',
            name='laptop_id1',
        ),
        migrations.AlterField(
            model_name='product',
            name='product_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
