# Generated by Django 4.2.4 on 2024-01-04 21:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0024_remove_dar_laptop_laptop_id1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chamberloginfo',
            name='chamber_id',
            field=models.ForeignKey(db_column='chamber_id', on_delete=django.db.models.deletion.CASCADE, to='database.chamber'),
        ),
    ]
