# Generated by Django 4.2.4 on 2024-01-10 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0025_alter_chamberloginfo_chamber_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='priority',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='test',
            name='status_log',
            field=models.CharField(max_length=4000, null=True),
        ),
    ]
