# Generated by Django 4.2.4 on 2024-01-11 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0026_test_priority_test_status_log'),
    ]

    operations = [
        migrations.RenameField(
            model_name='test',
            old_name='started_start',
            new_name='targeted_start',
        ),
    ]
