# Generated by Django 4.2.9 on 2024-01-29 16:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0027_rename_started_start_test_targeted_start'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='product_id',
            field=models.ForeignKey(db_column='product_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='database.product'),
        ),
        migrations.AddField(
            model_name='test',
            name='program_id',
            field=models.ForeignKey(db_column='program_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='database.program'),
        ),
        migrations.AlterField(
            model_name='program',
            name='program_name',
            field=models.CharField(max_length=50, null=True, unique=True, verbose_name='Program'),
        ),
    ]
