# Generated by Django 4.2.9 on 2024-02-06 20:35

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0028_test_product_id_test_program_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='test',
            name='cage_id',
            field=models.ForeignKey(db_column='cage_id', on_delete=django.db.models.deletion.CASCADE, to='database.cage', verbose_name='cage'),
        ),
        migrations.AlterField(
            model_name='test',
            name='chamber_id',
            field=models.ForeignKey(db_column='chamber_id', on_delete=django.db.models.deletion.CASCADE, to='database.chamber', verbose_name='chamber'),
        ),
        migrations.AlterField(
            model_name='test',
            name='channel_id',
            field=models.ForeignKey(db_column='channel_id', on_delete=django.db.models.deletion.CASCADE, to='database.darchannel', verbose_name='DAR'),
        ),
        migrations.AlterField(
            model_name='test',
            name='lab_id',
            field=models.ForeignKey(db_column='lab_id', on_delete=django.db.models.deletion.CASCADE, to='database.lab', verbose_name='Lab'),
        ),
        migrations.AlterField(
            model_name='test',
            name='technician_id',
            field=models.ForeignKey(db_column='technician_id', on_delete=django.db.models.deletion.CASCADE, to='database.technician', verbose_name='technician'),
        ),
        migrations.AlterField(
            model_name='test',
            name='test_map_id',
            field=models.ForeignKey(db_column='test_map_id', on_delete=django.db.models.deletion.CASCADE, to='database.testmap', verbose_name='Leg'),
        ),
        migrations.AlterField(
            model_name='test',
            name='test_type_id',
            field=models.ForeignKey(db_column='test_type_id', on_delete=django.db.models.deletion.CASCADE, to='database.testtype', verbose_name='Test'),
        ),
    ]
