# Generated by Django 4.2.9 on 2024-02-09 20:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0029_test_created_alter_test_cage_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
