# Generated by Django 4.2.9 on 2024-02-12 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0030_remove_test_channel_id_test_dar_id'),
        ('database', '0031_remove_test_channel_id_test_dar_id'),
    ]

    operations = [
    ]
